### ISSUE TITLE
Support for more features

### ISSUE THREAD

**Issue by relaxibus** [esp32beans/ESP32_flight_stick#1]
Hi, I found your project, very impressive. I'm looking for a ESP32 alternative to the FreeJoy project https://github.com/FreeJoy-Team/FreeJoy
Are you planning to add more features similar to the FreeJoy project?

**Comment by esp32beans** [comment]
Sorry, no FreeJoy is too complex for me. I made this primarily to create joysticks that work with the Xbox Adaptive Controller.

**Comment by tzmijevski** [comment]
Hey, your code works flawlessly with an ESP32S3 dev board. Congratulations and thank you very much!
Could you please teach me on how to add more buttons and axes?
I'm building a DIY Cessna simulator for PC, but I need 8 axes (aileron, elevator, rudder, throttle, propeller pitch, fuel mixture, left brake, right brake), and lots and lots of buttons.
Thanks in adavance!

**Comment by esp32beans** [comment]
I have not tried this but it appears to be much more flexible and powerful than this lib.

https://registry.platformio.org/libraries/schnoog/Joystick_ESP32S2
